#
# Makefile for heap
#

obj-y += heap.o

obj-$(CONFIG_MERGE_SORTED_ARRAYS) += merge_sorted_arrays.o
obj-$(CONFIG_SORT_K_INCREASING_DECREASING_ARRAY) += sort_k_increasing_decreasing_array.o
obj-$(CONFIG_FIND_CLOSEST_K_STARS) += find_closest_k_stars.o
obj-$(CONFIG_SORT_APPROXIMATELY_SORTED_ARRAY) += sort_approximately_sorted_array.o

subdir-$(CONFIG_HEAP_TEST) += test
