#
# Makefile for dsa
#

obj-$(CONFIG_BINARY_SEARCH) += binary_search.o
obj-$(CONFIG_BST_DFS) += bst_dfs.o
obj-$(CONFIG_BT_BFS) += bt_bfs.o
obj-$(CONFIG_BT_IN_ORDER) += bt_in_order.o
obj-$(CONFIG_BT_POST_ORDER) += bt_post_order.o
obj-$(CONFIG_BT_PRE_ORDER) += bt_pre_order.o
obj-$(CONFIG_BUBBLE_SORT) += bubble_sort.o
obj-$(CONFIG_COMPARE) += compare.o
obj-$(CONFIG_DOUBLY_LINKED_LIST) += doubly_linked_list.o
obj-$(CONFIG_LINEAR_SEARCH) += linear_search.o
obj-$(CONFIG_MAZE_SOLVER) += maze_solver.o
obj-$(CONFIG_DSA_QUEUE) += dsa_queue.o
obj-$(CONFIG_MIN_HEAP) += min_heap.o
obj-$(CONFIG_QUICK_SORT) += quick_sort.o
obj-$(CONFIG_DSA_STACK) += dsa_stack.o
obj-$(CONFIG_TWO_CRYSTAL_BALLS) += two_crystal_balls.o
obj-$(CONFIG_GRAPH_LIST_BFS) += graph_list_bfs.o
obj-$(CONFIG_GRAPH_MATRIX_BFS) += graph_matrix_bfs.o
obj-$(CONFIG_DIJKSTRA_LIST) += dijkstra_list.o
