abs_srctree := $(dir $(realpath $(lastword $(MAKEFILE_LIST))))
srcroot := .
builddir := $(srcroot)/build
configdir := $(srcroot)/include/config
DAY_NUM := $(words $(shell ls -d day* 2>/dev/null))
BUILD_CONFIG := $(srcroot)/.config

export srcroot abs_srctree builddir configdir DAY_NUM BUILD_CONFIG

daydir := day$(DAY_NUM)
BUILTIN_OBJS := $(patsubst %, $(builddir)/%/built-in.a, src)
ifeq ($(need_daydir),1)
BUILTIN_OBJS += $(patsubst %, $(builddir)/%/built-in.a, $(daydir)/src)
endif

include $(srcroot)/scripts/Makefile.include

PHONY := all
all:

PHONY := FORCE
FORCE:

# Generate day directories
PHONY += generate
generate:
	$(MAKE) $(generate)=src

$(BUILTIN_OBJS): $(configdir)/auto.conf $(configdir)/autoconf.h FORCE
	$(MAKE) $(build)=$(strip $(patsubst build/%/built-in.a, %, $@))

# Compile required sources

$(builddir)/built-in.a: $(BUILTIN_OBJS)
	rm -f $@
	$(AR) cDPrsT $@ $(real-prereqs)

LIBS += -lm

PHONY += main
main: $(builddir)/built-in.a
	$(CC) $(real-prereqs) -o $(builddir)/$@ $(LIBS)
	$(builddir)/$@

$(configdir)/auto.conf $(configdir)/autoconf.h: $(BUILD_CONFIG)
	$(file >$(configdir)/auto.conf,# Synced by $(BUILD_CONFIG))
	$(file >$(configdir)/autoconf.h,// Synced by $(BUILD_CONFIG))
	$(MAKE) $(config)=src

all: main

PHONY += unittest
unittest: $(TEST_OBJS) FORCE
	$(file >$(BUILD_CONFIG),# Freshly generated by make unittest)
	mkdir -p $(configdir)
	$(MAKE) $(runtarget)=src $(test) $(unittest) && \
		$(MAKE) -f Makefile need_daydir=0 $(unittest)

PHONY += clean
clean:
	rm -rf $(builddir)

PHONY += cleanall
cleanall: clean
	rm -rf $(configdir) day* $(BUILD_CONFIG)

day%:
	$(error Missing generated source in $@. Run make generate first!)

# Generate .config
PHONY += prepare_config
prepare_config:
	$(file >$(BUILD_CONFIG),# Freshly generated by make goals)
	mkdir -p $(configdir)

real-goals := $(filter-out $(PHONY), $(MAKECMDGOALS))
this-target := $(firstword $(real-goals))
ifneq ($(filter-out $(this-target), $(real-goals)),)
$(error Run must contain only one target)
endif

ifneq ($(this-target),)
$(this-target): $(daydir) prepare_config
	$(MAKE) $(runtarget)=src $(this-target) && \
		$(MAKE) -f Makefile need_daydir=1
endif

.PHONY: $(PHONY)
