#
# Makefile for map
#

obj-y += htable.o
obj-y += set.o

obj-$(CONFIG_CAN_PERFORM_PALINDROME) += can_perform_palindrome.o
obj-$(CONFIG_FIND_ALL_SUBSTRINGS) += find_all_substrings.o
obj-$(CONFIG_FIND_NEAREST_REPETITION) += find_nearest_repetition.o
obj-$(CONFIG_FIND_SMALLEST_SEQUENTIALLY_COVERING_SET) += find_smallest_sequentially_covering_set.o
obj-$(CONFIG_FIND_SMALLEST_SUBARRAY_COVERING_SET) += find_smallest_subarray_covering_set.o
obj-$(CONFIG_IS_LETTER_CONSTRUCTIBLE_FROM_MAGAZINE) += is_letter_constructible_from_magazine.o
obj-$(CONFIG_LONGEST_CONTAINED_RANGE) += longest_contained_range.o
obj-$(CONFIG_LONGEST_SUBARRAY_WITH_DISTINCT_ENTRIES) += longest_subarray_with_distinct_entries.o
obj-$(CONFIG_TEST_COLLATZ_CONJECTURE) += test_collatz_conjecture.o

subdir-$(CONFIG_MAP_TEST) += test
