#
# Makefile for recursion
#

obj-$(CONFIG_COMBINATIONS) += combinations.o
obj-$(CONFIG_GENERATE_BALANCED_PARENTHESES) += generate_balanced_parentheses.o
obj-$(CONFIG_GENERATE_POWER_SET) += generate_power_set.o
obj-$(CONFIG_N_QUEENS) += n_queens.o
obj-$(CONFIG_PERMUTATIONS) += permutations.o
obj-$(CONFIG_SOLVE_SUDOKU) += solve_sudoku.o
