#
# Makefile for bt
#

obj-y += btree_node.o

obj-$(CONFIG_CREATE_LIST_OF_LEAVES) += create_list_of_leaves.o
obj-$(CONFIG_FIND_KTH_NODE_BINARY_TREE) += find_kth_node_binary_tree.o
obj-$(CONFIG_FROM_PREORDER_INORDER) += from_preorder_inorder.o
obj-$(CONFIG_HAS_PATH_SUM) += has_path_sum.o
obj-$(CONFIG_INORDER_TRAVERSAL) += inorder_traversal.o
obj-$(CONFIG_IS_BALANCED_BINARY_TREE) += is_balanced_binary_tree.o
obj-$(CONFIG_IS_SYMMETRIC) += is_symmetric.o
obj-$(CONFIG_LOWEST_COMMON_ANCESTOR) += lowest_common_ancestor.o
obj-$(CONFIG_PREORDER_TRAVERSAL) += preorder_traversal.o
obj-$(CONFIG_RECONSTRUCT_PREORDER) += reconstruct_preorder.o
obj-$(CONFIG_SUM_ROOT_TO_LEAVE) += sum_root_to_leave.o

subdir-$(CONFIG_BINARY_TREE_TEST) += test
