#
# Makefile for bitwise
#

obj-$(CONFIG_ADD_BINARY) += add_binary.o
obj-$(CONFIG_REVERSE_BITS) += reverse_bits.o
obj-$(CONFIG_HAMMING_WEIGHT) += hamming_weight.o
obj-$(CONFIG_SINGLE_NUMBER) += single_number.o
obj-$(CONFIG_SINGLE_NUMBER_2) += single_number_2.o
obj-$(CONFIG_RANGE_BITWISE_AND) += range_bitwise_and.o
