package main

import (
	"bytes"
	"flag"
	"fmt"
	"go/ast"
	"go/parser"
	"go/printer"
	"go/token"
	"html/template"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"
	"time"
	"unicode"
)

func main() {
	log.SetFlags(log.LstdFlags | log.Lshortfile)
	day := flag.Bool("day", false, "Generating a new day")
	flag.Parse()

	if *day {
		generateDay()
	}
}

const (
	root    = "."
	scripts = "scripts"
)

var dayTemplate = template.Must(template.New("").Parse(`// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// {{ .Timestamp }}
package day

func {{ .Name }}({{ .Params }}) ({{ .Returns }}) {{ .Body }}
`))

func generateDay() {
	filename := filepath.Join(root, scripts, "define.go")
	_, err := os.Stat(filename)
	if err != nil && os.IsNotExist(err) {
		log.Fatalln("You need to update.", err)
	}

	var dayDir string
	count := 1
	for {
		dayDir = "day" + strconv.Itoa(count)
		_, err := os.Stat(filepath.Join(root, dayDir))
		if err == nil || !os.IsNotExist(err) {
			count++
			continue
		}
		break
	}

	os.Mkdir(dayDir, 0755)
	if err != nil {
		log.Fatalln(err)
	}

	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, filename, nil, parser.ParseComments)
	if err != nil {
		log.Fatal(err)
	}

	type ModuleTemplate struct {
		Timestamp string
		Name      string
		Params    string
		Body      string
		Returns   string
	}
	templates := make([]ModuleTemplate, 0)

	for _, decl := range node.Decls {
		funcDecl, ok := decl.(*ast.FuncDecl)
		if !ok {
			continue
		}

		// Exported = starts with uppercase letter
		if funcDecl.Recv != nil || !unicode.IsUpper([]rune(funcDecl.Name.Name)[0]) {
			continue
		}

		template := ModuleTemplate{
			Timestamp: time.Now().Format("2006-01-02 15:04:05"),
			Name:      funcDecl.Name.Name,
		}

		if funcDecl.Type.Params == nil {
			log.Fatalln("Unsupported empty params.")
		}

		var paramsBuf bytes.Buffer
		for _, param := range funcDecl.Type.Params.List {
			paramType := exprToString(fset, param.Type)

			// Handle unnamed parameters (e.g., func(int, string))
			if len(param.Names) == 0 {
				log.Fatalln("Unsupported unamed " + paramType)
			}

			for _, name := range param.Names {
				if paramsBuf.Len() != 0 {
					paramsBuf.WriteString(", ")
				}
				paramsBuf.WriteString(fmt.Sprintf("%s %s", name.Name, paramType))
			}
		}
		template.Params = paramsBuf.String()

		var outputsBuf bytes.Buffer
		for _, output := range funcDecl.Type.Results.List {
			outputType := exprToString(fset, output.Type)

			// Handle named returns (e.g., func () (a int, b string))
			if len(output.Names) != 0 {
				log.Fatalln("Unsupported named " + outputType)
			}

			outputsBuf.WriteString(outputType)
		}
		template.Returns = outputsBuf.String()

		if funcDecl.Body != nil {
			var buf bytes.Buffer
			err := printer.Fprint(&buf, fset, funcDecl.Body)
			if err != nil {
				log.Fatalln(err)
			}
			template.Body = buf.String()
		}

		templates = append(templates, template)
	}

	for _, template := range templates {
		f, err := os.Create(filepath.Join(root, dayDir, template.Name+".go"))
		if err != nil {
			log.Fatalln(err)
		}
		dayTemplate.Execute(f, template)
		f.Close()
	}

	{
		cmd := exec.Command("go", "mod", "init", dayDir)
		cmd.Dir = dayDir
		if err := cmd.Run(); err != nil {
			log.Fatalln(err)
		}
	}

	{
		cmd := exec.Command("go", "mod", "edit", "-replace=leetcode/day=./"+dayDir)
		cmd.Dir = root
		if err := cmd.Run(); err != nil {
			log.Fatalln(err)
		}
	}
}

func exprToString(fset *token.FileSet, expr ast.Expr) string {
	var buf bytes.Buffer
	if err := printer.Fprint(&buf, fset, expr); err != nil {
		return "<error>"
	}
	return buf.String()
}
