out-obj := $(build_dir)/$(obj)

PHONY := $(out-obj)/
$(out-obj)/:

subdir-y :=
obj-y :=

-include $(srcroot)/include/config/auto.conf
include $(srcroot)/scripts/Makefile.include
include $(srcroot)/$(obj)/Makefile

real-subdir := $(addprefix $(out-obj)/, $(subdir-y))
real-obj-y := $(patsubst %.o, $(out-obj)/%.o, $(obj-y))
real-obj-y += $(addsuffix /built-in.a, $(real-subdir))

CFLAGS += -I$(srcroot)/src  -I$(srcroot)/include

# Compile C sources:
$(out-obj)/%.o: $(obj)/%.c
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) -c $< -o $@

# Compile precompile headers:
$(out-obj)/%.gch: $(obj)/%.h
	@mkdir -p $(dir $@)
	$(CC) $(CFLAGS) $< -o $@

# Descend to subdir:
$(out-obj)/%/built-in.a: $(obj)/%
	$(MAKE) $(build)=$^

# Link built-in:
$(out-obj)/built-in.a: $(real-obj-y)
	$(AR) rcT $@ $^

$(out-obj)/: $(out-obj)/built-in.a ;

.PHONY: $(PHONY)
