src := $(srcroot)/$(obj)

subdir-y :=
subdir- :=
obj-y :=
obj- :=

include $(srcroot)/scripts/Makefile.include
include $(srcroot)/$(obj)/Makefile

real-obj := $(patsubst %.o, $(src)/%.o, $(obj-))
real-subdir := $(addprefix $(src)/, $(subdir-) $(subdir-y))

PHONY := $(obj)/
$(obj)/:

PHONY += $(real-subdir)
$(real-subdir):
	$(MAKE) $(config)=$@
	$(call add_config, $(notdir $@))

$(obj)/%.o:
	$(call add_config, $(patsubst $(obj)/%.o, %,$@))

$(obj)/: $(real-obj) $(real-subdir) ;

syncconfig:
	cp $(srcroot)/$(BUILD_CONFIG) $(config_dir)/auto.conf

.PHONY: $(PHONY)
