build := -f $(srcroot)/scripts/Makefile.build obj
config := -f $(srcroot)/scripts/Makefile.config obj
runtarget := -f $(srcroot)/scripts/Makefile.target obj

to_lower = $(shell echo $(1) | tr A-Z a-z)
to_upper = $(shell echo $(1) | tr a-z A-Z)

