src := $(srcroot)/$(obj)

subdir-y :=
subdir- :=
obj-y :=
obj- :=

include $(srcroot)/scripts/Makefile.include
include $(srcroot)/$(obj)/Makefile

real-obj := $(patsubst %.o, $(src)/%.o, $(obj-))
real-subdir := $(addprefix $(src)/, $(subdir-) $(subdir-y))

PHONY := $(obj)/
$(obj)/:

PHONY += $(real-subdir)
$(real-subdir):
	$(MAKE) $(config)=$@
	mkdir -p $(config_dir)
	touch $(config_dir)/CONFIG_$(call to_upper, $(notdir $@))

$(obj)/%.o:
	mkdir -p $(config_dir)
	touch $(config_dir)/CONFIG_$(call to_upper, $(patsubst $(obj)/%.o, %,$@))

$(obj)/: $(real-obj) $(real-subdir) ;

.PHONY: $(PHONY)
