src := $(srcroot)/$(obj)

PHONY := $(obj)/
$(obj)/:

subdir-y :=
subdir- :=
obj-y :=
obj- :=

include $(srcroot)/scripts/Makefile.include
include $(srcroot)/$(obj)/Makefile

real-obj := $(patsubst %.o, $(src)/%.o, $(obj-))
real-subdir := $(addprefix $(src)/, $(subdir-) $(subdir-y))

if_cfg_enabled = $(if $(shell grep -e '^$(target-cfg)=y\s*' $(BUILD_CONFIG)), \
	$(file >>$(configdir)/autoconf.h,#define $(target-cfg) 1) \
	$(file >>$(configdir)/auto.conf,$(target-cfg)=y), \
	$(file >>$(configdir)/auto.conf,# $(target-cfg) is not set))

$(subdir-y): ;

$(subdir-): target-cfg = CONFIG_$(call to_upper, $@)
$(obj)/%.o: target-cfg = $(call to_upper, $(patsubst $(obj)/%.o, CONFIG_%, $@))

$(subdir-):
	$(call if_cfg_enabled, $(target-cfg))

$(obj)/%.o:
	$(call if_cfg_enabled, $(target-cfg))

$(real-subdir): $(obj)/%: %
	$(MAKE) $(config)=$@

$(obj)/: $(real-obj) $(real-subdir) ;

.PHONY: $(PHONY)
