build := -f $(srcroot)/scripts/Makefile.build obj
config := -f $(srcroot)/scripts/Makefile.config obj
runtarget := -f $(srcroot)/scripts/Makefile.target obj
generate := -f $(srcroot)/scripts/Makefile.generate obj

to_lower = $(shell echo $(1) | tr A-Z a-z)
to_upper = $(shell echo $(1) | tr a-z A-Z)

get_basename = $(basename $(notdir $(1)))
config_name = $(addprefix CONFIG_, $(call get_basename, $(1)))

add_config = touch $(1)

RED := "\033[0;31m"
GREEN := "\033[0;32m"
YELLOW := "\033[0;33m"
COLOR_OFF :="\033[0m"

error_msg = @echo -e $(RED) $(1) $(COLOR_OFF)
info_msg = @echo -e $(GREEN) $(1) $(COLOR_OFF)
warn_msg = @echo -e $(YELLOW) $(1) $(COLOR_OFF)
