#
# Makefile for src
#

obj-y += main.o pch.gch

obj-$(CONFIG_UTILS) += utils/
obj-$(CONFIG_ARRAY_STRING) += array_string/
obj-$(CONFIG_LINKED_LIST) += linked_list/
obj-$(CONFIG_STACK) += stack/
obj-$(CONFIG_RECURSION) += recursion/
obj-$(CONFIG_BINARY_TREE) += binary_tree/
obj-$(CONFIG_QUEUE) += queue/
