#
# Makefile for linked list
#

obj-$(CONFIG_ADD_TWO_NUMBERS) += add_two_numbers.o
obj-$(CONFIG_CYCLICALLY_RIGHT_SHIFT_LIST) += cyclically_right_shift_list.o
obj-$(CONFIG_DELETION_FROM_LIST) += deletion_from_list.o
obj-$(CONFIG_EVEN_ODD_MERGE) += even_odd_merge.o
obj-$(CONFIG_HAS_CYCLE) += has_cycle.o
obj-$(CONFIG_IS_LINKED_LIST_A_PALINDROME) += is_linked_list_a_palindrome.o
obj-$(CONFIG_LIST_NODE) += list_node.o
obj-$(CONFIG_LIST_PIVOTING) += list_pivoting.o
obj-$(CONFIG_MERGE_TWO_SORTED_LISTS) += merge_two_sorted_lists.o
obj-$(CONFIG_OVERLAPPING_LISTS) += overlapping_lists.o
obj-$(CONFIG_OVERLAPPING_NO_CYCLE_LISTS) += overlapping_no_cycle_lists.o
obj-$(CONFIG_REMOVE_DUPLICATES) += remove_duplicates.o
obj-$(CONFIG_REMOVE_KTH_LAST) += remove_kth_last.o
obj-$(CONFIG_REVERSE_SUBLIST) += reverse_sublist.o
