#
# Makefile for stack
#

obj-$(CONFIG_EVALUATE) += evaluate.o
obj-$(CONFIG_EXAMINE_BUILDING_WITH_SUNSET) += examine_building_with_sunset.o
obj-$(CONFIG_IS_WELL_FORMED) += is_well_formed.o
obj-$(CONFIG_SHORTEST_EQUIVALENT_PATH) += shortest_equivalent_path.o
