#
# Makefile for array string
#

obj-$(CONFIG_APPLY_PERMUATATION) += apply_permutation.o
obj-$(CONFIG_BUY_AND_SELL_STOCK_ONCE) += buy_and_sell_stock_once.o
obj-$(CONFIG_BUY_AND_SELL_STOCK_TWICE) += buy_and_sell_stock_twice.o
obj-$(CONFIG_CAN_REACH_END) += can_reach_end.o
obj-$(CONFIG_CONVERT_BASE) += convert_base.o
obj-$(CONFIG_DELETE_DUPLICATES) += delete_duplicates.o
obj-$(CONFIG_DUTCH_FLAG_PARTITION) += dutch_flag_partition.o
obj-$(CONFIG_GENERATE_PASCAL_TRIANGLE) += generate_pascal_triangle.o
obj-$(CONFIG_GENERATE_PRIMES) += generate_primes.o
obj-$(CONFIG_INT_TO_STRING) += int_to_string.o
obj-$(CONFIG_IS_PALINDROME) += is_palindrome.o
obj-$(CONFIG_IS_VALID_SUDOKU) += is_valid_sudoku.o
obj-$(CONFIG_LOOK_AND_SAY) += look_and_say.o
obj-$(CONFIG_MATRIX_IN_SPIRAL_ORDER) += matrix_in_spiral_order.o
obj-$(CONFIG_MERGE) += merge.o
obj-$(CONFIG_MULTIPLY) += multiply.o
obj-$(CONFIG_NEXT_PERMUTATION) += next_permutation.o
obj-$(CONFIG_PLUS_ONE) += plus_one.o
obj-$(CONFIG_RABIN_KARP) += rabin_karp.o
obj-$(CONFIG_REMOVE_ELEMENT) += remove_element.o
obj-$(CONFIG_REPLACE_AND_REMOVE) += replace_and_remove.o
obj-$(CONFIG_REVERSE_WORDS) += reverse_words.o
obj-$(CONFIG_ROMAN_TO_INTEGER) += roman_to_integer.o
obj-$(CONFIG_ROTATE_MATRIX) += rotate_matrix.o
obj-$(CONFIG_SNAKE_STRING) += snake_string.o
obj-$(CONFIG_SPREADSHEET_DECODE_COLUMN_ID) += spreadsheet_decode_column_id.o
obj-$(CONFIG_STRING_DECODING) += string_decoding.o
obj-$(CONFIG_STRING_ENCODING) += string_encoding.o
obj-$(CONFIG_STRING_TO_INT) += string_to_int.o
